### PR TITLE
Updated the Image of Sales Forecast Issue# 278

### PR DESCRIPTION
**Pull request by rahmatzeb**
Added an illustrative picture from SILK Corp Images.

### CODE REVIEW

**Comment by rahmatzeb** [comment]
@Aini-Bashir please review this pull request.

**Review by Aini-Bashir — CHANGES_REQUESTED** [review]
Upload image as well

**Comment by rahmatzeb** [comment]
@Aini-Bashir Please check it now.

**Review by Aini-Bashir — CHANGES_REQUESTED** [review]
This image is not appropriate, I mean how it is representing Sales forecast. Visit Envato and find something from there and past ethe link in that specific issue and mention me so I can download it for you. Thanks.

**Comment by rahmatzeb** [comment]
@Aini-Bashir. Here is the link: [Link] [https://envato-shoebox-0.imgix.net/c57a/ee3b-7f8a-4075-96d7-1b75751d3270/b_grzes31.jpg?auto=compress%2Cformat&fit=max&mark=https%3A%2F%2Felements-assets.envato.com%2Fstatic%2Fwatermark2.png&markalign=center%2Cmiddle&markalpha=18&w=800&s=88e8c6e5a547b4b88320f67048d9f7cf]

**Comment by rahmatzeb** [comment]
Link: [](https://envato-shoebox-0.imgix.net/c57a/ee3b-7f8a-4075-96d7-1b75751d3270/b_grzes31.jpg?auto=compress%2Cformat&fit=max&mark=https%3A%2F%2Felements-assets.envato.com%2Fstatic%2Fwatermark2.png&markalign=center%2Cmiddle&markalpha=18&w=800&s=88e8c6e5a547b4b88320f67048d9f7cf)

**Comment by Aini-Bashir** [comment]
@rahmatzeb, send the link again. Write the "Link" and then press ctrl+k, it will pop up a screen where you'll paste the link and insert it. Thanks

**Comment by rahmatzeb** [comment]
Okay, let me do it again. 
Link[](urhttps://envato-shoebox-0.imgix.net/c57a/ee3b-7f8a-4075-96d7-1b75751d3270/b_grzes31.jpg?auto=compress%2Cformat&fit=max&mark=https%3A%2F%2Felements-assets.envato.com%2Fstatic%2Fwatermark2.png&markalign=center%2Cmiddle&markalpha=18&w=800&s=88e8c6e5a547b4b88320f67048d9f7cfl)

**Comment by rahmatzeb** [comment]
Asset 1: [Link]([https://envato-shoebox-0.imgix.net/c57a/ee3b-7f8a-4075-96d7-1b75751d3270/b_grzes31.jpg?auto=compress%2Cformat&fit=max&mark=https%3A%2F%2Felements-assets.envato.com%2Fstatic%2Fwatermark2.png&markalign=center%2Cmiddle&markalpha=18&w=800&s=88e8c6e5a547b4b88320f67048d9f7cf)

**Review by Alisha-Rashid — APPROVED** [review]

**Review by SuzyQuant — APPROVED** [review]

**Review by SuzyQuant — APPROVED** [review]

**Pull request merged**
