### PR TITLE
Updated the issue #26

### PR DESCRIPTION
**Pull request by Aiko-Kawamura**

### CODE REVIEW

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Please incorporate the points from this Table of Contents for SILK Arts
https://github.com/NoteHive/Silk-Corp-Guide/blob/gh-pages/research/TableOfContents.md

Edit "human activities" too.

**Review by Remy-Reveltek — CHANGES_REQUESTED** [review]
@Aiko-Kawamura, please have a training session with Aini or any other team member to learn how you can make changes directly to the website. You are updating your text in .md files.

**Comment by Aiko-Kawamura** [comment]
@Remy-Reveltek, @SuzyQuant. Please review, I made changes to the content of this PR. Thanks.

**Comment by Aiko-Kawamura** [comment]
I made changes to the content of this PR. Thanks.

**Review by Remy-Reveltek — CHANGES_REQUESTED** [review]
Your paragraph started with the title name, as the title is already written in the section heading. There's no need to repeat it at the beginning of your paragraph.

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Remove quotation mark ""

**Pull request closed without merging**
