### PR TITLE
Updated "Balance Sheet," issue# 283

### PR DESCRIPTION
**Pull request by Aini-Bashir**
I updated the source of the image here.

### CODE REVIEW

**Review by rahmatzeb — APPROVED** [review]

**Review by Alisha-Rashid — APPROVED** [review]

**Review by rahmatzeb — APPROVED** [review]
That's great...

**Comment by rahmatzeb** [comment]
@Aini-Bashir, I want to work on this issue as well. Can you please down this picture?
Asset 1: [link][https://envato-shoebox-0.imgix.net/57e8/039c-974d-4c34-81f4-cab8afa79b62/3S2A8770.jpg?auto=compress%2Cformat&fit=max&mark=https%3A%2F%2Felements-assets.envato.com%2Fstatic%2Fwatermark2.png&markalign=center%2Cmiddle&markalpha=18&w=800&s=a3f3616e25efdca69d8fc1633eabe966]

**Comment by rahmatzeb** [comment]
Also, tell me how to upload link like this LINK, THAT you mostly upload.

**Comment by Aini-Bashir** [comment]
Use ctrl + k to make the link pretty. This issue is not related to the update of image and it's also completed. Work on the Sales forecast issue as I commented for changes there.

**Review by Alisha-Rashid — APPROVED** [review]

**Review by SuzyQuant — APPROVED** [review]

**Pull request merged**
