### PR TITLE
Updated the SILK Cafe, issue# 220

### PR DESCRIPTION
**Pull request by Aini-Bashir**
I updated the source of the image for SILK Cafe.

### CODE REVIEW

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Don't put any spaces in assets.

silk_yoga.jpg
silkYoga.jpg

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Change the naming convention of your photo as well. It should reflect the name of what you used in the code in this same issue.

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Change the naming convention of your jpg photo as well. It should reflect the same name as your other commit.

**Comment by Aini-Bashir** [comment]
Yes, I change both the source narration and photo narration. 
image
image

**Pull request merged**
