### PR TITLE
Updated definition issue #28

### PR DESCRIPTION
**Pull request by Aiko-Kawamura**

### CODE REVIEW

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Please incorporate the points from this Table of Contents for SILK Home
https://github.com/NoteHive/Silk-Corp-Guide/blob/gh-pages/research/TableOfContents.mdv

**Comment by Aiko-Kawamura** [comment]
I made changes on this PR, I incorporated the points provided from the link above.

**Review by Remy-Reveltek — CHANGES_REQUESTED** [review]
I did not like that your paragraph started with the title name, as the title is already written in the section heading. There's no need to repeat it at the beginning of your paragraph.

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Re-write and don't include SILK Homes and Silk Corp in the sentences.

**Pull request closed without merging**
