### PR TITLE
Updated Image for Building on Success Issue# 273

### PR DESCRIPTION
**Pull request by rahmatzeb**
I updated the source of the image from SILK Corp Guide

### CODE REVIEW

**Review by Aini-Bashir — CHANGES_REQUESTED** [review]
@rahmatzeb, can you please make sure if the size of image is according to the requirements. Because it's showing too large image and upon inspecting its showing dimensions of 885 x 570 something.
Thanks.

**Comment by rahmatzeb** [comment]
Yeah, let me change it.

**Comment by rahmatzeb** [comment]
@Aini-Bashir, can you please tell how to change picture? will I have to upload it again or change it somewhere...

**Comment by Aini-Bashir** [comment]
@rahmatzeb, Work again on this issue

**Review by Aini-Bashir — CHANGES_REQUESTED** [review]
image
You're doing same mistake again and again.

**Pull request closed without merging**
