### PR TITLE
Updated Dummy Content of Conclusion

### PR DESCRIPTION
**Pull request by rahmatzeb**

### CODE REVIEW

**Comment by rahmatzeb** [comment]
@Aini-Bashir Please review this pull request.

**Comment by rahmatzeb** [comment]
Ok, that's right @Aini-Bashir . Should I adjust it again?

**Comment by Aini-Bashir** [comment]
Yes, @rahmatzeb do it again. These days we are working on media content for the guide, so if you want to learn how to do that you're welcome to shadow me while working.

**Comment by rahmatzeb** [comment]
@Aini-Bashir okay will do that again. Also, I want to learn how to start working on media content, please tell me how to do that... And what does it mean to shadow you?

**Comment by Aini-Bashir** [comment]
Shadow me means watch me while I am working on how to update the media content.

**Comment by rahmatzeb** [comment]
@Aini-Bashir That's right. I made a few changes in this PR that you had suggested. Now it's a little bit above the exact character count. Please have a look at it. Also, I want you to guide me as well on how to work on media content.

**Review by Aini-Bashir — CHANGES_REQUESTED** [review]
image
The last part of this line "License" also needs to be changed.

**Comment by rahmatzeb** [comment]
Okay, let me change it as well.

**Comment by rahmatzeb** [comment]
@Aini-Bashir what if I remove this word "License" completely.

**Comment by Aini-Bashir** [comment]
You wouldn't be following the character count then because you can't remove it from the SILK Guide template.

**Comment by rahmatzeb** [comment]
Ok, let me try... will let you know once i am done with it.

**Comment by rahmatzeb** [comment]
Aini, please check it now.

**Comment by rahmatzeb** [comment]
There is this code  </a> between the text, should I remove it or not.

**Review by Aini-Bashir — CHANGES_REQUESTED** [review]
The original character count is 43 only. I would say leave this area for now maybe we change the template for conclusion area because this one line is not enough to explain conclusion for the whole guide.

**Comment by rahmatzeb** [comment]
That's right.

**Comment by rahmatzeb** [comment]
What should I focus on? Also, I want to know about the current activity that you are working on...

**Comment by Aini-Bashir** [comment]
Please close this pull request as well as we need to plan about the template layout for the conclusion area of guide.

**Pull request closed without merging**
