### PR TITLE
Updated issue #29

### PR DESCRIPTION
**Pull request by Aiko-Kawamura**

### CODE REVIEW

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Please incorporate the points from this Table of Contents for SILK Cafe
https://github.com/NoteHive/Silk-Corp-Guide/blob/gh-pages/research/TableOfContents.md

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Please incorporate the points from this Table of Contents
https://github.com/NoteHive/Silk-Corp-Guide/blob/gh-pages/research/TableOfContents.md

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Please incorporate the points from this Table of Contents
https://github.com/NoteHive/Silk-Corp-Guide/blob/gh-pages/research/TableOfContents.md

**Review by Remy-Reveltek — APPROVED** [review]

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Incorporate SILK Tech from Table of Contents

**Pull request closed without merging**
