### PR TITLE
Update image for Respectful issue#211

### PR DESCRIPTION
**Pull request by Alisha-Rashid**
I updated the issue#211 for Respectful in "Our culture".

### CODE REVIEW

**Review by Aini-Bashir — CHANGES_REQUESTED** [review]
The image source narration is too long it may disturb the file structure. Please use few words to update.

**Review by Aini-Bashir — CHANGES_REQUESTED** [review]
image
When you update the source of image, you also need to change the name of image. Now, in your commits here the source is different and name of image is different.

**Comment by Alisha-Rashid** [comment]
ok I work on these things again.

**Review by SuzyQuant — APPROVED** [review]

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Need to reflect the same name between the image and in the code.

**Pull request closed without merging**
