### PR TITLE
Upload photo for location of Pakistan, Issue#243

### PR DESCRIPTION
**Pull request by Alisha-Rashid**
Creative Commons Attribution-ShareAlike 4.0 International License
https://commons.wikimedia.org/wiki/File:Lake_Saif-ul-malook_Pakistan.jpg

### CODE REVIEW

**Review by Aini-Bashir — CHANGES_REQUESTED** [review]
You didn't change the source of this image.

**Review by Aini-Bashir — CHANGES_REQUESTED** [review]
Work gain on this issue from the start

**Comment by Alisha-Rashid** [comment]
Okay, I will do it from the start.

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
Don't put any spaces in assets and don't capitalize the first letter. For example,

silk_yoga.jpg
silkYoga.jpg
silk.jpg

**Comment by Aini-Bashir** [comment]
@Alisha-Rashid, please redo this pull request.

**Comment by Alisha-Rashid** [comment]
Okay, @Aini-Bashir I'll re-do this pull request.

**Comment by Aini-Bashir** [comment]
Please close this one as well as worked on this area again. Thanks

**Pull request closed without merging**
