### PR TITLE
Updated definition of issue #27

### PR DESCRIPTION
**Pull request by Aiko-Kawamura**

### CODE REVIEW

**Comment by Aiko-Kawamura** [comment]
submitted pull request for the issue #27

**Comment by Aiko-Kawamura** [comment]
I updated content on this PR and change title. 

@Remy-Reveltek I can't add label and milestone, it's grayed out on my side.

**Comment by Remy-Reveltek** [comment]
@Aiko-Kawamura, I guess Mr. Hackney gave you access to fill out the PR dashboard.

**Comment by Aiko-Kawamura** [comment]
@Remy-Reveltek  Done adding labels and linked the milestone.

**Review by Remy-Reveltek — CHANGES_REQUESTED** [review]
Issue was to update text directly to the https://guide.silkcorp.org/

**Comment by Aiko-Kawamura** [comment]
I made changes in Silk Cafe contents and add the important points with reference links included.

**Pull request closed without merging**
