### PR TITLE
Updated synopsis.md

### PR DESCRIPTION
**Pull request by rahmatzeb**
I updated the synopsis for SILK guide.

### CODE REVIEW

**Comment by rahmatzeb** [comment]
@Aini-Bashir , I updated the Synopsis, please go through it and suggest changes.

**Review by Aini-Bashir — COMMENTED** [review]
Tomorrow we'll create a mermaid roadmap according to this synopsis and will see if this synopsis gives a good and clear direction to our roadmap. 
Thanks for updating the synopsis.

**Comment by rahmatzeb** [comment]
Alright...

**Review by Alisha-Rashid — APPROVED** [review]

**Review by SuzyQuant — CHANGES_REQUESTED** [review]
I believe I only said to put the shorter synopsis (like 1 sentence) with the roadmap below it at the top of your current content for an easy read. Basically, it should be like this is what I was expecting

 

Title

Synopsis (Short Version)

Roadmap (Gantt Chart)

---

Your Existing Synopsis (Long Version)

**Comment by Aini-Bashir** [comment]
Alright. Let me correct it

**Pull request closed without merging**
